### ISSUE TITLE
soaplite nMax error message

### ISSUE THREAD

**Issue by bartolsthoorn** [SINGROUP/dscribe#24]
Small thing: the number of basis functions can go up to 13, but the error message says 12, which one is it?
```
soaplite/core.py, line 107, in get_soap_locals
    assert nMax <= 13, "number of basis functions cannot exceed 12. nMax={}".format(nMax)
```

**Comment by lauri-codes** [comment]
Hi @bartolsthoorn,

This assertion is actually obsolete. Thanks for pointing it out. There is no single hard limit for nmax as it depends on rcut as well, see issue #19. This check has been now changed in the master branch. You can try it out by installing directly from source git with the instructions found [here](https://singroup.github.io/dscribe/install.html). This change will also be added to the next release, but I'm not sure when it's going to be out.

The code has now been changed so that instead of checking a hardcoded limit, the code will try to do the orthonormalization with the current rcut and nmax, and raise an error if the orthonormalization is numerically unstable.

**Comment by bartolsthoorn** [comment]
OK thank you!
