### ISSUE TITLE
MBTR Weighting function

### ISSUE THREAD

**Issue by sirmarcel** [SINGROUP/dscribe#27]
Hi everyone, 

another quick question: In MBTR, is the `exp` weighting function always using the distance? I.e. is the `x` in `exp(-s*x)` the distance?

Thanks,

Marcel

**Comment by lauri-codes** [comment]
Hi,

For k=2, x is the distance between the two atoms. For k=3, x is the length of the triangle perimeter formed by the three atoms, A->B->C->A.

This is mentioned [here](https://singroup.github.io/dscribe/doc/dscribe.descriptors.html#dscribe.descriptors.mbtr.MBTR) but not in the tutorials. I will add something about it.

**Comment by sirmarcel** [comment]
Very good! Thank you. One more question:

In this paragraph:

> DScribe achieves the completely identical MBTR output for different periodic supercells by taking into account the translational multiplicity of the atomic pairs and triples in the system. This is done in practice by weighting the contribution of the pair and triples by how many different periodic repetitions of the original cell are involved in forming the pair or triple.

Is this an intrinsic side-effect of using `l2_each`, i.e. normalising the `k`-terms by `l2`, or are you doing something additionally to get this to work?

**Comment by lauri-codes** [comment]
Also a very good question: The normalization alone is not sufficient in order to get completely identical output. Basically I have in the code a part that ensures that only one translationally unique combination of atoms (doubles, triples) is included for periodic systems. In periodic systems the system is extended beyond the cell boundaries, and thus the same combination may be repeated multiple times. This multiplicity is reduced by the code, as otherwise completely identical output for different cell shapes and sizes is not achieved (together with the normalization).

If you want to know more about this, I suggest opening up a new issue where I can give more details.

**Comment by sirmarcel** [comment]
Thank you!! Let's discuss further in #28.
