### ISSUE TITLE
MBTR Normalisation Details

### ISSUE THREAD

**Issue by sirmarcel** [SINGROUP/dscribe#28]
Hi @lauri-codes,

As mentioned in #27, I'd be *very* interested in learning a bit more about how the MBTR normalisation works under the hood, and how you manage to reduce double-counting in case of supercells, and how all of this relates to normalisation. Wouldn't removing symmetrically identical pairs/triplets already ensure identical MBTRs, regardless of normalisation?

Cheers,

Marcel

**Comment by lauri-codes** [comment]
Hi @sirmarcel,

Ok, here goes my explanation on the topic using an example:

Let's consider a toy system that is periodic and has just two identical atoms. These atoms are 1 angstrom apart in the x-axis, but have the same y and z coordinates. The simulation cell is cubic 10Å x 10Å x 10Å, with cell vectors along the cartesian coordinates. Now let's consider two ways to position the two atoms within the cell: **1)** we put them in the middle **2)** we put them at the cell borders, e.g. first at x=0, second at x=9.

These two alternatives however represent the exact same material (remember the cell is periodic). In fact there are also other cell shapes, sizes and ways to position the atoms within the cell that still represent the same material.

Now let's consider calculating MBTR k=2 for these two alternatives. We will have to use some weighting, as the system is periodic. Let's say that the weighting goes to zero at the distance of 5Å. For 1) we would then just have **one** distance to take into account for k=2: 1Å. The periodic repetitions are too far and the weighting cuts them out. For 2), however, we will have to repeat the cell periodically in +/- x direction. This has to be done because the periodic copies are in fact very close. After expanding the system we will see that now there are **two** distances at 1 Å.

If we thus follow the definition of the original article (assuming that I have interpreted all the math and text correctly) we will get these two different results for the same system. Note that the cell size is the same, so it is not a supercell. Normalization would in this case get rid of the problem (although it should not be necessary, the systems are identical!), but for more complex cases even normalization will not help anymore, as subtle differences will start to appear in the shapes. The DScribe implementation of MBTR adds a new check that is meant to correct for this error. The code keeps track of which periodic repetition of the original cell the atoms belong to. **If two atoms for which we calculate the spectrum belong to different cells, their contribution is halved** because each such pair must have been counted twice due to the periodicity. The same logic applies for triples, but slightly altered: **if the three atoms belong to two different cells, their contribution is once again halved. If they belong to three different cells, their contribution is divided by three**, as this combination must have been included three times.

As to your question _Wouldn't removing symmetrically identical pairs/triplets already ensure identical MBTRs, regardless of normalisation?_: The reduction of translational multiplicity as described above only accounts for the translational symmetry as defined by the **provided cell**. Thus it does not know the true translational symmetry of the system (it's not that smart :)  ). So even if the above explained method is applied, a 1x1x1 cell and a 2x2x2 cell would have a difference of 8 in the amplitude of the MBTR output. But this is then easily removed by normalization (much easier than first reducing the system to the primitive cell, although that is also an option).

Hopefully this helps. Unfortunately I'm not able to wrap this discussion into neat equations, so I have to rely on these examples. I'm happy to discuss the topic more and maybe there are even better ways for doing this exact same thing.

**Comment by sirmarcel** [comment]
Thanks for the thorough explanation. I think I understand your approach now.

As far as I know, in `qmmlpack` (the original MBTR implementation), this problem is tackled in a different way: One index is always kept inside the original unit cell, so you don't get double-counting when extending the unit cell. I think this is identical in outcome to your approach, but I might be wrong. I'll try this out with the examples from the docs when I have a spare minute!

**Comment by lauri-codes** [comment]
Hi,

Actually the method of demanding one index to be inside the original unit cell does not prevent the double counting entirely. I did try that at first (it was mentioned in the arXiv paper as well), but it was not sufficient enough. It does prevent double counting for combinations that are contained entirely within one cell, but not the double counting of atomic combinations that cross the boundary of two cells.

**Comment by sirmarcel** [comment]
Hi Lauri,

sorry to keep bothering you! Can you give an example for when this happens (or is the one you give above one)? I'm having a hard time visualising it, and I want to make sure I get it right...!

**Comment by lauri-codes** [comment]
Hi @sirmarcel,

The above example is the clearest example that I can think of which demonstrates the core problem of double counting pairs/triples that span across cell borders.

In the package itself the lines of code that prevent the double counting are 128-132 (for k=2) and 234-243 (for k=3) of **dscribe/libmbtr/mbtr.cpp** in the current version (master branch commit 087600deb5d985dec955dfa7e470193c26af281b). If you want you can take a look at those lines and see the logic behind them.

**Comment by lauri-codes** [comment]
Closing for now, reopen if needed.

**Comment by sirmarcel** [comment]
Thanks Lauri -- I haven't forgotten about this. I'm a bit busy with other stuff, but I'll come back to this. I ran a few tests and the difference in implementation is causing some kind of odd discrepancies between `qmmlpack` and `dscribe` that I want to get to the bottom of. For your simple example, for instance, both seem to be precisely identical, but not for the supercells in your tutorial. Something's afoot!

**Comment by sirmarcel** [comment]
Hi @lauri-codes,

I'm having some trouble really understanding your example above. I think `qmmlpack` takes the perspective that distances are always (unless you explicitly de-duplicate) counted directionally, so by default *everything* is double-counted, which... also yields a consistent result in your example?

Here is me trying to illustrate the approaches:

```

(**** is the unit cell, ----- are replicaes, | is the cell boundary)

"qmmlpack"

a:
|----------|**********|-----------|
|   x-x    |   a-b    |    x-x    |
|----------|**********|-----------|

We have: a->b, b->a. 2 Distances.

b:
|----------|***********|----------|
|x        x-a         b-y        x|
|----------|***********|----------|

We have: a->x. b->y. 2 Distances.

"dscribe?"

c:
|----------|**********|-----------|
|   x-x    |   a-b    |    x-x    |
|----------|**********|-----------|

We have: a-b. 1 Distance.

d:
|----------|***********|----------|
|x        x-a         b-y        x|
|----------|***********|----------|

We have: a-x. b-y. 2 Distances, but counted as 0.5. So 1 distance.
```

Have I correctly understood your perspective? If yes, do you think there's anything wrong with the `qmmlpack` way?

Thanks again!

**Comment by lauri-codes** [comment]
Hi @sirmarcel,

In the case of pairwise terms (k=2) it is indeed functionally identical if you double the distances (=consider the directionality) that are entirely within the original cell (`qmmlpack`) or half the distances that go beyond the original cell (`dscribe`). Both achieve the same goal, but the output differs by a constant of two.

The problem arises when considering triplets (k=3), where simply doubling or tripling the terms inside the cell does not work anymore.

**Comment by sirmarcel** [comment]
Hm, okay... Do you also have a minimal example for this case? I'm really sorry to keep jammering about this, but somehow I'm finding it extremely difficult to reason about this. 😬

**Comment by lauri-codes** [comment]
Hi @sirmarcel,

Don't worry, I've also struggled with this.

Here is a minimal example for k=3. Lets say that we can consider atoms only in the xy-plane (it is just easier to visualize, the logic extends to 3D).

```

(**** is the unit cell, ----- are replicas, | is the cell boundary, 
each two-digit number represents an atom)

|--------|--------|--------|
| 01  02 | 03  04 | 05  06 |
|--------|********|--------|
| 07  08 | 09  10 | 11  12 |
|--------|********|--------|
| 13  14 | 15  16 | 17  18 |

```

The original cell now has two atoms: 09 and 10. For simplicity lets only consider triplets with the smallest L-shape.

Triplets 03-09-10 and 09-15-16 are translationally symmetric copies of the same atoms. DScribe detects this by investigating how many cells the atoms in these triplets span: in this case the atoms span 2 different cells, thus the weight is divided by 2.

Triplets 02-08-09, 04-10-11 and 10-16-17 are translationally symmetric copies of the same atoms DScribe detects this by investigating how many cells the atoms in these triplets span: in this case the atoms span 3 different cells, thus the weight is divided by 3.

This logic continues applies for all triplets: if the original cell has >= 3 atoms, some triplets will be completely within one cell -> their contribution is divided by 1. By ensuring that each translationally symmetric combination is only considered once, the output becomes invariant against different cell sizes and shapes.

Does this make sense?

**Comment by sirmarcel** [comment]
Hi Lauri,

Sorry once again for the long delay. Thanks for the explanation!

I've had a closer look at `qmmlpack` and the differences between its MBTR and the one in `dscribe` appears to be purely numerical, there are no double-counting issues in either code for supercells, and with the example we started the thread with. So somehow, the `qmmlpack` approach also works, without explicitly adjusting counts with factors as you do.

I think the way it works is by *always* counting every contribution (if the 'full' indexing is used), and so basically systematically, but consistently, over-counting. The perspective is not "within this arrangement of atoms, what unique angles/distances can we find", but rather "starting from this atom, which angles/distances can I find" -- the latter doesn't really care about the unit cell or replicas. 

In your example above, there would be:

Starting from 09: 
09-10-04, 09-10-16, 
09-03-04, 09-03-02, 
09-08-02, 09-08-14, 
09-15-14, 09-15-16

Starting from 10:
(you get the idea, the above but shifted one step to the right)

Now if you were to do a 2x2 supercell, you'd just get 4x the counts, but still exactly the same angles, since every atom sees the same environment. You just have more "starting points".

Does this make some sense?

(If you want to investigate this in further detail, I'm sure we can arrange access to `qmmlpack`. I unfortunately am quite busy with wrapping up the long-delayed benchmark paper and can't spare too much time to think about this!)

**Comment by lauri-codes** [comment]
Hi @sirmarcel,

I think I see. So as you say `qmmlpack` probably achieves the same effect by not caring about finding unique combinations and simply summing up all combinations it can find. I think the effect is the same, just the number of combinations to go through is larger.
