### ISSUE TITLE
MBTR k=2 Question

### ISSUE THREAD

**Issue by sirmarcel** [SINGROUP/dscribe#32]
Hi Lauri,

Sorry to bother you again! I have two questions about the MBTR implementation.

1) Is there a reason that `normalize_gaussians=True` returns Gaussians which are one at `x=mu`? I would expect the exact opposite to be true, since a Gaussian normalised to integrate to 1 would usually not have that value at its center.
2) Does the `distance` and `inverse_distance` behave differently on purpose?

Here is some example code with my questions...

```python

from dscribe.descriptors import MBTR
from ase import Atoms

atoms = [Atoms(positions=[[0.0, 0.0, 0.0], [2.0, 0.0, 0.0]], numbers=[1, 1])]

a = {
    "k2": {
        "grid": {"min": 0, "max": 1, "n": 3, "sigma": 0.0001},
        "geometry": {"function": "inverse_distance"},
        "weighting": {"function": "unity", "cutoff": 0.001},
    },
    "normalization": "none",
    "normalize_gaussians": True,
    "flatten": True,
    "sparse": False,
    "species": [1],
}

mbtr = MBTR(
    k2={
        "grid": {"min": 0, "max": 1, "n": 3, "sigma": 0.0001},
        "geometry": {"function": "inverse_distance"},
        "weighting": {"function": "unity", "cutoff": 0.001},
    },
    normalize_gaussians=True,
    species=[1],
    periodic=False,
)

print(mbtr.create(atoms))
# => [[0. 2. 0.]]
# should this not be [0, 1, 0]? There should be only one inverse distance?

mbtr = MBTR(
    k2={
        "grid": {"min": 0, "max": 1, "n": 3, "sigma": 0.0001},
        "geometry": {"function": "inverse_distance"},
        "weighting": {"function": "unity", "cutoff": 0.001},
    },
    normalize_gaussians=False,
    species=[1],
    periodic=False,
)

print(mbtr.create(atoms))
# => [[0.         0.00050133 0.        ]]
# I thought a *normalised* Gaussian would have this value.

mbtr = MBTR(
    k2={
        "grid": {"min": 1, "max": 3, "n": 3, "sigma": 0.0001},
        "geometry": {"function": "distance"},
        "weighting": {"function": "unity", "cutoff": 0.001},
    },
    normalize_gaussians=True,
    species=[1],
    periodic=False,
)

print(mbtr.create(atoms))
# => [[0. 1. 0.]]
# This is as expected.


mbtr = MBTR(
    k2={
        "grid": {"min": 1, "max": 3, "n": 3, "sigma": 0.0001},
        "geometry": {"function": "distance"},
        "weighting": {"function": "unity", "cutoff": 0.001},
    },
    normalize_gaussians=False,
    species=[1],
    periodic=False,
)

print(mbtr.create(atoms))
# => [[0.         0.00025066 0.        ]]
# See above!
```

This is on the most recent release version, `0.2.9`.

Thanks!

**Comment by lauri-codes** [comment]
Hi @sirmarcel,

In short: this behaviour you are seeing is intentional and is related to the way the discretization of the Gaussians behaves when using very low number of discretization points (in your case n=3). As soon as you crank up the number of points you will see that this "effect" disappears. See below if interested.

Longer version: To calculate the value of the discretized Gaussians, dscribe uses the cumulative distribution function of a normal distribution: CDF(x). The value at a grid point x is calculated by calculating using a simple finite difference: MBTR(x) = (CDF(x+dx/2) - CDF(x-dx/2) )/dx. By using this approach the normalization of the Gaussians is ensured even with a very low number of discretization points (as seen in your case, where the area under the three points always sums up to 1 as intended). If the implementation would directly use the Gaussian probability distribution, the area under the Gaussians would slightly depend on their location when using small number of discretization points. I wanted to avoid this and thus chose the described option. Both approaches converge to the same result when n is reasonably large.

Good question, hope this clears things up!

**Comment by sirmarcel** [comment]
Hi @lauri-codes,

Thanks for the prompt and in-depth reply! I think I understand your approach, and the observed "weirdness" is due to a combination of a) very low `sigma` and b) low `n`, right?

**Comment by lauri-codes** [comment]
Yes.
