### ISSUE TITLE
Exact SOAP cutoff treatment

### ISSUE THREAD

**Issue by sirmarcel** [SINGROUP/dscribe#34]
Hi Lauri,

Another question, this time about your SOAP implementation. (The background is that I'm so far finding consistent performance differences between yours (yours seems to work slightly better ;)) and `quippy`, and I want to have at least a rough idea of implementation differences.)

How exactly are you treating the `rcut` parameter? I have taken a brief look at the code and it seems like you're in the periodic case extending the cutoff to determine the replicas to use, but also the actual computation functions seem to add some number to the cutoff -- what's going on? If I set `rcut=5`, will any atoms be included that are further away than that?

**Comment by lauri-codes** [comment]
Hi Marcel,

Nice to hear that you are not seeing any major differences in performance!

The difference between `quippy` SOAP and `dscribe` SOAP has been discussed [in the old project repository](https://github.com/SINGROUP/SOAPLite/issues/6). Please check that discussion, although it does not provide a direct answer. Fully answering this question would require someone who knows both the `quippy` code and the `dscribe` code in and out.

Regarding the "padding" that is added in extending the system for periodic systems: If you use the polynomial radial basis set (rbf="polynomial"), anything beyond rcut is never taken into account, as the radial basis goes exactly to zero after the cutoff. So the padding is actually entirely unnecessary (maybe I could take it out with an if-statement...) However, the default radial basis set uses Gaussians (rbf="gto") which don't exactly go to zero at the cutoff, just to a very low value. Because of this, a padding is needed to avoid boundary effects from atoms that are close to the cutoff value and would be visible in this "tail" of the Gaussians.

Hope this helps

**Comment by sirmarcel** [comment]
Okay, thanks for the clarification! I think that's enough for now. :)
