### ISSUE TITLE
How to deal with training set with different number of species using SOAPlite?

### ISSUE THREAD

**Issue by wushanyun64** [SINGROUP/dscribe#35]
Hi,
I'm a little bit confused with the size of the output descriptor.  Based on the document of SOAPlite, I understand that the size is partially dependent on the number of species in the structure (Ts), however, what if I want to train an ML model with a training set containing structures with different number of species? In that case, the size of the output descriptor will be different from each other which will prevent the following machine learning process right?  Am I understanding this wrong or there are some ways to fix this problem?

**Comment by lauri-codes** [comment]
Hi @wushanyun64,

First of all, I would suggest using the `dscribe` interface directly instead of the deprecated SOAPLite repository. `dscribe` provides all the same functionality but is actively maintained.

As to the original question: Yes, you are right that the output size depends on how many chemical species are involved. When creating the SOAP output you should provide all the chemical species that will be included in your entire training+test sets, not just the species that are present in a single structure. This way the size will be fixed for each sample. If you are using the `dscribe` interface, the species are provided through the [species-argument in the SOAP constructor](https://singroup.github.io/dscribe/doc/dscribe.descriptors.html#dscribe.descriptors.soap.SOAP). You can find examples of its usage in the [SOAP tutorials](https://singroup.github.io/dscribe/tutorials/soap.html). If you insist on using the SOAPLite interface, the corresponding variable is `all_atomtypes` e.g. in the function `soaplite.get_periodic_soap_locals`.

Hope this helps!
