### ISSUE TITLE
average soap

### ISSUE THREAD

**Issue by gabor1** [SINGROUP/dscribe#44]
hi!

When you compute the soap vector of a structure using the "average=True" argument, what do you average over? Do you compute the soap vector for each atomic environment and then return the average of that over atoms? This is much less useful than the kind of average that the QUIP code does, which is to compute the Ylm expansion around each atom, average _those_, and then square that average vector to get the single soap vector of the structure. This latter method retains the orientation relationships between the different environments, and is invariant only with respect to a global rotation of the entire structure. The first way is invariant to rotations of each environment separately.

**Comment by lauri-codes** [comment]
Hi @gabor1!

Yes, we indeed simply average over the power spectrum of each atom. The method you described does certainly sound better. Just to be super clear, you mean that instead of simply averaging the power spectrum of each atom (the math will take a second to render):

<img src="https://render.githubusercontent.com/render/math?math=p_{nn'l}^{Z_1,Z_2} \sim \frac{1}{n} \sum_i \sum_m (c_{nlm}^{i, Z_1})* (c_{n'lm}^{i, Z_2})">

(where _i_ sums over the atoms and _n_ is the total number of atoms in the structure) we would put the summation inside the power spectrum coefficients:

<img src="https://render.githubusercontent.com/render/math?math=p_{nn'l}^{Z_1,Z_2} \sim \sum_m (\frac{1}{n} \sum_i c_{nlm}^{i, Z_1})* (\frac{1}{n} \sum_i c_{n'lm}^{i, Z_2})">

Can you point to any possible references that discuss this kind form of averaging? Once you verify that I understood correctly, I can think about how to get it implemented. Thanks a lot!

**Comment by gabor1** [comment]
Your formulae are correct. I think the first mention of this is in here

https://pubs.acs.org/doi/10.1021/acs.jpclett.8b01067

(We've had it in the code for a long time but didn't use it very much until recently).

Of course if users want the average of the soap vectors they can just call the function without this flag and then average the array themselves. The point is that the kind of average I'm talking about isn't accessible unless you provide those option.

-- Gábor

**Comment by lauri-codes** [comment]
Now added this average mode in 0.4.0. It can be activated with `average="inner"`.

**Comment by gabor1** [comment]
thanks!
