### ISSUE TITLE
Slow generation of kernels

### ISSUE THREAD

**Issue by arosen93** [SINGROUP/dscribe#45]
Currently, the implementation of `dscribe.kernels.localsimilaritykernel.LocalSimilarityKernel.create` is quite slow if dealing with a large number of samples, each of which has a very large SOAP matrix. I imagine this is because of the many calls of `C_ij = self.get_pairwise_matrix(x_i, y_j)` as you loop through every pair of materials (excluding symmetric ones). Calculating the SOAP matrices is extremely quick in comparison to running the results through the `AverageKernel`.

Are there any plans to increase the efficiency of this process? Right now, I have (for example) 10,000 materials and am looking to get the (10,000 x 10,000) average kernel matrix from SOAP features. So, what I'm doing right now is splitting the single calculation up into 10,000 calculations of calculating the (1 x 10,000) matrix and then appending the results together in the end. Obviously, this embarrassingly parallel solution isn't particularly efficient, and even these individual calculations are quite slow. For the record, each of my materials has ~100 atoms (and the species span most of the periodic table, unfortunately).

Just for clarity, the fully serial workflow (excluding the data splitting process) looks something like the following. The massive bottleneck is at the calculation of `kernel_avg_train`.

```python

structures_train = read('structures.xyz', index=':') #all structures

#Get all unique species from structures
species = []
for structure in structures:
	syms = np.unique(structure.get_chemical_symbols()).tolist()
	for sym in syms:
		if sym not in species:
			species.append(sym)

soap = SOAP(
    species=species,
    periodic=True,
    rcut=4.0,
    nmax=8,
    lmax=6,
    sparse=True
)

#Make SOAP fingerprints
#NOTE: Normally, I split this step up to prevent huge memory overhead
#No problem here if I do the above (and it's quite fast)
soaps_train = soap.create(structures_train)
save_npz('soaps_train.npz',soaps_train)

fingerprints_train = []
old_idx = 0
#Restructure SOAP fingerprints
for structure_train in structures_train:
	n_atoms = len(structure_train)
	soap_j = soaps_train[old_idx:old_idx+n_atoms,:]
	old_idx += n_atoms
	fingerprints_train.append(soap_j)

# Calculates the similarity kernel matrix of dimensions (n_train x n_train)
avg_train = AverageKernel(metric="linear")
kernel_avg_train = avg_train.create(fingerprints_train) #slow step, even if split up over individual chunks!
np.savetxt('soap_kernel_train.csv',kernel_avg_train,delimiter=',')
```

**Comment by lauri-codes** [comment]
Hi @arosen93!

Just to be clear: are you sure that you want to calculate the `AverageKernel` and not something else? I would expect that if you are working with such big structures and large amount of them, you would instead want to work with a _single averaged global descriptor per structure_ instead of AverageKernel (as is done in many cases, e.g. in the DScribe article). Especially, if you are only using `metric="linear"` in `AverageKernel`, you can get the same exact result much faster by simply working with a single descriptor per structure that is an average over all atoms in that structure.

If, however, you really want to work with constructing the similarity by individually comparing the local sites, I'm afraid I don't have very good suggestions for going around the time complexity, which seems to be fixed at around `O(n_structures^2*n_atoms_per_structure^2)`. The simplest speedup that I could think for this is the embarrassingly parallel version that you have already tried, but maybe spread over multiple nodes as NumPy will probably already try to efficiently use all cores on a single machine.

Hope this helps!

**Comment by arosen93** [comment]
Hi @lauri-code!

Thank you for taking the time to reply. I will say I'm not 100% certain (only because I am very new to this field). I was trying to reproduce the protocol in this paper (https://onlinelibrary.wiley.com/doi/abs/10.1002/qute.201900023), where the authors say they used an average kernel to get a global similarity kernel for kernel ridge regression. How would one go about calculating this single averaged global descriptor per structure? I see in the dscribe paper it says "we also include results using a simple averaged SOAP output for all atoms in the simulation cell." Is this simply, for instance, the average value of all the rows in the SOAP matrix for a given structure? I will do some more reading to see approaches other than generating kernels (e.g. an average kernel or the REMatch kernel) for describing the global (as opposed local) structure.

Thanks for the suggestion regarding the time-consuming nature of the kernel calculation. That is what I figured, but I wanted to double-check.

**Comment by arosen93** [comment]
P.S. Super minor docfix. In the tutorials page for SOAP [here](https://singroup.github.io/dscribe/tutorials/soap.html), the last block of code uses `soap_peroxide`, which isn't defined in the doc (the h2o2 molecule is created but no SOAP object created for that molecule). There's just a disconnect between the example script and the live docs.

**Comment by lauri-codes** [comment]
Hi @arosen93,

Ok, great! Indeed your script very nicely demonstrates how the two different will give the same result (when using a linear metric). In SOAP the `average=True` indeed already takes the average of all atoms in the structure. Thanks for the docfix, now updated.
