### ISSUE TITLE
symmetry of terms for multi-species descriptor

### ISSUE THREAD

**Issue by gabor1** [SINGROUP/dscribe#48]
HEllo there!

I have a comment about the way you compute the SOAP descriptor for multiple species. In your docs page, you quote the nested loops as (omitting the l loop)

loop z
  loop z' >= z'
    loop n
      loop n' >=n

If there are N radial basis functions and Z species, this has N(N+1)Z(Z+1)/4 terms. 

In the QUIP code, we do something different. We create a combined index nz which has length N*Z, and the corresponding loops are

loop nz
  loop (nz)' >= (nz)

This has NZ(NZ+1)/2 terms, which is larger than yours. I believe that yours is incorrect, because you miss some terms. when z=z' you correctly omit n'<n terms, but when z != z', you still omit them, even though you should not, because when the two atoms are different, there is no symmetry that makes those terms the same as the n'>n terms.

**Comment by lauri-codes** [comment]
Hi Gabor!

Thanks for reporting this. I think I understand your point. I will have to check our implementation to see if we are truly misusing symmetry here. If so, this should be fixed ASAP.

**Comment by gabor1** [comment]
Thanks. A direct test would be to compute the elements I am talking about and to see if they match with the ones you think they match with… If they do, then we need to fix quip!

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by gabor1** [comment]
it's a funny terminology to label this "enhancement" ...

**Comment by lauri-codes** [comment]
I looked at this briefly, and indeed it seems to be a bug on our side. Now labeled correctly. Now I just need to find the time to fix it.

**Comment by gabor1** [comment]
Thanks. I haven't explicitly said, but perhaps should, that I am a keen supporter of other implementations of SOAP (especially ones like dscribe with improved radial basis), the quippy one is just for reference.

**Comment by lauri-codes** [comment]
Great, your input is very much appreciated!

**Comment by lauri-codes** [comment]
This is more of a note for future reference:

The individual terms in the multi-species power spectrum are of the form: <img src="https://render.githubusercontent.com/render/math?math=p_{nn'l}^{ZZ'} \sim \sum_m (c_{nlm}^{Z})* (c_{n'lm}^{Z'})">

So the question is, what terms are redundant due to symmetry? One way to analyze the symmetries is by taking the complex conjugate of the power spectrum (taking the complex conjugate doesn't affect the result as the power spectrum terms are real numbers):

<img src="https://render.githubusercontent.com/render/math?math=\sum_m (c_{nlm}^{Z})* (c_{n'lm}^{Z'}) = \left(\sum_m (c_{nlm}^{Z})* (c_{n'lm}^{Z'})\right)* =\sum_m (c_{nlm}^{Z}) (c_{n'lm}^{Z'})* = \sum_m (c_{n'lm}^{Z'})*(c_{nlm}^{Z})">

This shows that swapping both n and Z simultaneously creates identical output:
  <img src="https://render.githubusercontent.com/render/math?math=p_{nn'l}^{Z Z'} = p_{n'nl}^{Z' Z}">

As @gabor1 already mentioned, this symmetry can be very neatly taken into account by using combined indices (Z,n) and (Z',n') and adding only values for which (Z',n') >= (Z,n). The combined indices can be represented directly as python tuples as they have a suitable comparison operator.

**Comment by lauri-codes** [comment]
Now fixed in 0.4.0. Thanks again @gabor1!

**Comment by gabor1** [comment]
great, thanks!
