### ISSUE TITLE
analytical derivatives w.r.t Cartesian coordinates

### ISSUE THREAD

**Issue by coolcodecamper** [SINGROUP/dscribe#49]
Dear developers,
do you see the possibility to implement and output option for analytical derivatives with respect to Cartesian coordinates for SOAPs in the near future?
Kind regards,
coolcodecamper

**Comment by lauri-codes** [comment]
Dear @coolcodecamper,

This is a topic that has been asked quite often (duplicate of #14).

Implementing the analytical derivatives for SOAP using the GTO radial basis should be possible. It, however, is fairly large undertaking and we don't currently have the resources to do it ourselves. Implementing the derivatives for other descriptors should be easier.

We are open to contributions, so If this is something you could implement we would be more than happy to include it. In practice, numerical derivatives with finite-difference should also be a possibility since individual evaluations of SOAP are fairly fast.

Hope this helps

**Comment by coolcodecamper** [comment]
Thank you for your reply.
