### ISSUE TITLE
Docs seem to be broken

### ISSUE THREAD

**Issue by jdagdelen** [SINGROUP/dscribe#55]
All google results for docs lead to broken pages. Thought you might want to know.

**Comment by lauri-codes** [comment]
Thanks for the heads up. We had to change the documentation URL schema a bit due to versioning. This is causing the dead links. In the future, all links should refer to [https://singroup.github.io/dscribe/latest/](https://singroup.github.io/dscribe/latest/) which should always stay active irrespective of the current version.
