### ISSUE TITLE
API wishlist: convenience function to obtain all derivatives at once

### ISSUE THREAD

**Issue by coolcodecamper** [SINGROUP/dscribe#56]
Dear developers,

I very much appreciate your efforts and progress in the development of Cartesian derivatives for the available descriptors!
Here I would like to note that It would be very convenient to have a function that returns all derivatives at once, ideally in some kind of Jacobian matrix.
Taking the Coulomb matrix descriptor as an example, each matrix element q would have its own column of the Jacobian. The rows would then contain the derivatives by all atom coordinates.
Jacobian:
```
        (dq1/d_atom1_x   dq2/d_atom1_x   ...)
        (dq1/d_atom1_y   dq2/d_atom1_y   ...)
dq/dx = (dq1/d_atom1_z   dq2/d_atom1_z   ...)
        (dq1/d_atom2_x   dq2_d_atom2_x   ...)
        (      :              :           . )
```
More generally speaking, the Jacobian would have `3*number_of_atoms` rows and `length_of_flattened_descriptor` columns.

I am looking forward to the next release!

Best regards,
coolcodecamper

**Comment by lauri-codes** [comment]
Hi @coolcodecamper,

As you say we are just now taking the first steps in getting this implemented. As we have limited experience in using the derivatives we are not sure what would be the ideal output shape.

Currently we were planning an output with shape [n_atoms, 3, n_features] (the second dimension goes over x, y, z components). Do you think that a 2D Jacobian matrix would be a better solution instead of this kind of 3D Jacobian? On one hand 2D output would nice as it can very simply be provided both as sparse and dense arrays (scipy sparse matrices can only be 2D). On the other hand, I think that having a better separation between the output components would make their usage easier.

Additionally, local descriptors like SOAP are typically calculated at several different locations in an atomic system. This means that we need one extra dimension in the derivatives output for each of these locations.

Your input is very much appreciated. Also others are very welcome to join this discussion.

**Comment by coolcodecamper** [comment]
I am happy as long as the output is some numpy array containing all derivatives in a logical consistent shape. Then it should be straight-forward to reshape the output to 2D. In my case, I compute local descriptors for all atomic positions and flatten the output. So again my Jacobian is 2D.
I guess you are on the right track as it is probably easier to reduce dimensions of multi-dimensional output, than the increase dimensions of low-dimensional output.

**Comment by lauri-codes** [comment]
In 1.0.0 the derivatives are available for all atoms and multiple systems (currently SOAP only). We chose to return the derivatives as multi-dimensional arrays since this way as much of the layout information is preserved and it is easy to relayout it to whatever form you want. Closing for now.
